docs/api/rest-api.md, mkdocs.yml
Added links to static api docs (will be active once Ciprian updates deployment)
Also added links to EU and US server swagger UI.
Once merged to master, will work with Ciprian to publish docs.
=> added api-docs link to www docs. 

docs/monitoring/chef-recipe.md, docs/monitoring/spm-faq.md
Rename of:
- app-token into monitoring-token
- setup-spm into setup-sematext
These are docs specific to "our" spm-client (not the public one) so changes should be good (they don't fully apply to public AA though).
=> SC-3625 www docs adjustments for token/rec rename

docs/integration/solr.md, docs/integration/solrcloud.md
I adjusted the Solr and SolrCloud monitoring pages in the docs to include material from our Monitoring Solr with Sematext blog post.
=> Extract Solr monitoring to docs pages

docs/logs/special-fields.md, docs/monitoring/tag-support.md
- Renamed `Related special tags` to `Synonymous Tags`
- Minor changes to reserved special tags and move error related tags to Logs section
=> SC-4132: Tag docs updates

docs/agents/sematext-agent/containers/configuration.md, docs/agents/sematext-agent/containers/installation.md, docs/agents/sematext-agent/index.md, docs/agents/sematext-agent/processes/configuration.md, docs/agents/sematext-agent/processes/enable-process-monitoring.md, docs/agents/sematext-agent/processes/metrics.md, docs/monitoring/containers.md, docs/monitoring/processes.md, mkdocs.yml
I've removed redundant content from monitoring > processes and monitoring > containers instead adding links to more detailed pages under sematext agent > processes and sematext agent > containers. Screenshots below.
Monitoring > Containers
Sematext Agent > Containers > Installation
Monitoring > Processes
Sematext Agent > Processes > Enable/Disable
Sematext Agent > Processes > Metrics
=> Unify dupes for process and container monitoring pages and relevant STA pages

docs/agents/sematext-agent/packages/configuration.md, docs/agents/sematext-agent/packages/data.md, docs/monitoring/inventory.md, mkdocs.yml
This PR adds a new section to explain available configuration options related to package collection. It also contains a new page that describes which package data is gathered.
=> Add `Packages` section to Sematext Agent

docs/team/account-access.md, docs/team/app-access.md, docs/team/app-transfer.md, docs/team/index.md, docs/team/user-roles.md, mkdocs.yml
Took the copy from FAQ and created a dedicated section for Team and Access Sharing, with pages for:
- Overview
- Account Access
- App Access
- App Transfer
- User Roles
=> Added Team and Access Sharing sections and guides

.gitignore, docs/guide/integrations-guide.md, docs/integration/kafka.md, docs/integration/mongodb.md, docs/integration/solr.md, docs/integration/solrcloud.md, docs/monitoring/spm-faq.md
This PR adjusts docs:
- adds instructions how to gather agent logs in container environments
- de-duplicates mentions of "create diagnostics package" by linking them to single FAQ entry that covers everything
- adjusts some naming to match recent changes in SC (Package Installation -> Agent Installation AND Client/Agent Configuration Setup -> Agent Setup)
=> SC-5756 added container diag instructions; deduplicated some old stuff

docs/experience/user-identification.md
Added information on how to use custom tags to User Identification page. I've added a new section there.
=> Add custom tags documentation

docs/logagent/installation-docker.md
@megastef user on Hubspot reported that we use `IGNORE_LOGS_PATTERNS` instead of `IGNORE_LOGS_PATTERN`. This PR fixes it.
=> Fix issue reported by the user

docs/tags/common-schema.md
Added to Logs tags:
- span.id
- trace.id
Added span.id, trace, trace.id to reserved tags, though that is kind of redundant if we have the above four reserved by Logs, right?
Removed  reserved tags:
- span
- trace
And I assume we will be adding tags reserved for tracing, though we may not have anything we want to reserve just yet?
=> Added span* and trace* to Logs

docs/integration/kubernetes-audit-integration.md, mkdocs.yml
I've added a page for the Kubernetes Audit Logs integration under integrations. I can move this page under Kubernetes when that page gets added.
=> SC-7068: added K8s audit logs integration page

docs/logagent/filters.md
Removing this list because we have separate pages for input and output filters and we don't want to have this outdated and incomplete list here.
=> Removed an old, incomplete list of filters

docs/tags/common-schema.md
Hi, 
This PR adds the Logagent `geoip` fields to common schema. During that I also changed the fields that the iOS and Android libraries are sending, so they are now sending the `geoip.location` just like Logagent does. This was done for consistency reasons. It was easier to change that in the libraries - less users, close to no issues with backwards compatibility.
=> Add geoip section to Logs common schema

docs/integration/generic-logs-integration.md
This PR fixes a few broken link on the Generic Logs Integration page.
I also updated the list of integrations to match our UI instructions, and added a section about AWS Lambda logs with a reference to the Github repo and blog post explaining it.
=> Fix broken links on Generic Logs Integration page

docs/integration/ibm-cloud-kubernetes-logs.md, docs/logagent/input-filter-containerd.md, docs/logagent/output-filter-dropevents.md, mkdocs.yml
Added a page explaining how to set up Kubernetes logging for the IBM Cloud Kubernetes Service that runs on the Containerd runtime.
=> SC-8659: Added logs docs for IBM Cloud Kubernetes Service

mkdocs.yml
Hi, 
A quick addition, the link to `Browser SDK` in the `Experience` section of the docs. I think we don't need additional description we can just open the page from `Agents` section that we already have. It looks like this:
=> SC-9558 - Add Browser SDK section to Experience

docs/agents/browser.md, docs/experience/on-page-transaction.md
This PR adjusts the Experience docs to reflect that we can now override custom tags for single transaction.
=> Adjust docs to reflect new tags changes re transactions

docs/experience/faq.md
Just another FAQ explaining when page loads might be missing from Experience Apps.
=> Add faq about missing page loads

docs/logs/field-types.md, docs/logs/fields.md, docs/logs/index-events-via-elasticsearch-api.md, docs/logs/mappings-templates.md, mkdocs.yml
Hi guys, 
This PR introduces templates and mappings dedicated section to Logs docs. It shows how to use templates and what it means to use mappings. I have another docs JIRA on me regarding the fields editor, which will bring some additional information on data structure and SC Logs. I think that when it comes to templates this is enough. 
The page looks as follows:
=> Docs for Logs templates and mappings

docs/monitoring/reports-and-components.md
There are two such links:
* one in [this section](https://sematext.com/docs/monitoring/reports-and-components/#monitoring-report-menu), which I think should point to the Split Screen *section*
* the second one is on the [Split Screen section](https://sematext.com/docs/monitoring/reports-and-components/#split-screen) which says "learn more", so I guess it should point to the separate page: https://sematext.com/docs/guide/split-screen/
=> fix 404s for split screen

docs/integration/express.js.md, docs/integration/node.js.md
The docs didn't have an explanation of how to configure a Nodejs app running in container envs so it works with our agents.
=> Added container instructions for nodejs/expressjs integration

docs/synthetics/faq.md
This PR adds an entry to FAQ on filtering requests from Synthetics monitors based on User-Agent header.
=> Add entry for User-Agent information

docs/experience/browser-memory.md
As the Chrome Origin Trials for browser memory usage measurements ended I adjusted the docs to reflect that and to inform users that the feature is available starting from Chrome 89.
=> Adjust memory measurement browser compatibility information

docs/agents/sematext-agent/installation.md, docs/monitoring/spm-faq.md
Info for SELinux users
SELinux is preventing sematext-agent processes from running in some cases. This PR adds the docs for SELinux users. Separately, I'll adjust rpm/deb installers to check whether it is enabled and print a link to FAQ entry if it is.
=> SC-10932 info for SELinux users in relation to sematext-agent rpm/deb

docs/experience/browser-memory.md
Move closer to top of page to make limitations more visible for users.
=> Move memory api limitations section to make more visible

docs/logagent/installation-windows.md
To show that backslashes need to be escaped.
=> Add Windows file input example

docs/tags/common-schema.md
I will remove https://sematext.com/docs/events/fields/ page after review to avoid duplicate content. And add a nav link at the bottom https://sematext.com/docs/events/adding/ page saying "See common Sematext Common Schema for recommended event fields."
=> Events fields and tags added to common schema

docs/fleet/index.md
Added one more possible cause for the Log Shipper status "Not Configured", related with Kubernetes permissions.
=> Update fleet troubleshooting

docs/integration/akka.md, docs/integration/elasticsearch-integration.md, docs/integration/hbase.md, docs/integration/jenkins.md, docs/integration/kafka.md, docs/integration/opensearch-integration.md, docs/integration/solr-integration.md
- This PR adds a section for default alert rules in all integrations supporting them.
- Each alert rule contains a description, an example and a list of actions to be taken. 
- Each action is limited to a short description on what the user should do.
=> SC-16400 add default ARs in integrations

docs/synthetics/puppeteer-scripts/README.md, docs/synthetics/puppeteer-scripts/multiple-page-load-times.js, docs/synthetics/puppeteer-scripts/single-page-app.js
Some of our Synthetics Browser monitor UJS examples used our live demos. Since that functionality has been removed, these have been rewritten to keep the examples relevant and up-to-date. I have also tested that these new examples worked fine for multiple runs from all our predefined locations, and added the missing description for the _Multiple Page Load Times_ example to our docs.
=> SC-19984 Rewrite Synthetics UJS examples which used Live Demos

docs/synthetics/playwright-scripts/README.md, docs/synthetics/playwright-scripts/apple-store.js, docs/synthetics/playwright-scripts/basic-ntlm-authentication.js, docs/synthetics/playwright-scripts/custom-metric-json.js, docs/synthetics/playwright-scripts/custom-metric.js, docs/synthetics/playwright-scripts/fetch-use-token.js, docs/synthetics/playwright-scripts/google-play.js, docs/synthetics/playwright-scripts/load-web-page.js, docs/synthetics/playwright-scripts/login-wiki.js, docs/synthetics/playwright-scripts/multi-tab.js, docs/synthetics/playwright-scripts/multiple-page-load-times.js, docs/synthetics/playwright-scripts/navigate-specific-page.js, docs/synthetics/playwright-scripts/open-search-page.js, docs/synthetics/playwright-scripts/request-interception.js, docs/synthetics/playwright-scripts/shopping-cart.js, docs/synthetics/playwright-scripts/single-page-app.js, docs/synthetics/playwright-scripts/text-search.js, docs/synthetics/playwright-scripts/use-sensitive-data.js
I create a folder similar to Puppeteer scripts and added all the scripts with Puppeteer replacing by Playwright. I have tested all these scripts again so you don't have to do that at all. If you want to review the scripts its better to just review their comments or some usage.
The Readme file for most parts is the same as before with reference to Puppeteer removed and minor changes based on the script changes I made.
=> Add Playwright example scripts and readme

docs/integration/docker.md
@cpipilas the link is broken, redirects to https://sematext.com/docs/integration/docker/infra
I updated to https://sematext.com/docs/integration/infra/.
I cannot deploy this fix till Matija is back, so you can approve the new link till then.
=> ful_NO-JIRA-fix-infra-link

mkdocs-material-overrides/main.html
Since we had to implement a custom script for the 'Edit this page" feature, this PR improves it and covers all possible cases.
The issue is that the actual file path in the document structure doesn't always match the URL path that MkDocs generates.
- For most regular pages (like /logs/settings/), MkDocs URLs end with a slash, but the actual file is just logs/settings.md (not logs/settings/index.md).
- For section overview pages (like /logs/), the file is usually logs/index.md.
- Some special cases exist, like /logs/discovery/ which maps to logs/discovery/intro.md rather than logs/discovery/index.md.
A mapping function has been implemented that:
- Uses a dictionary of special cases for known URL patterns, especially for main section indexes and some exceptions like the discovery page.
- …
=> Update 'edit this page' script to cover all cases

docs/synthetics/ci-cd/ci-cd-self-hosting.md, docs/synthetics/faq.md, mkdocs.yml
Adds an example of how to work around limitations regarding GitHub Actions Minutes. The linked repo has also been made public, so it'll serve as an example of what the implementation could look like.
=> SC-22027 Add self-hosted runner info
