sematext/docs

docs/sematext-docker-agent/configuration.md

Fixes https://github.com/sematext/sematext-agent-docker/issues/41

Document LOGSENE_ENABLE_DEFAULT

---

docs/logs/syslog-ng.md

* updated links
* changed transport=tcp to transport=tls for the TLS section
* set minimum version to 3.4
* updated CA md5

Updated syslog-ng documentation

---

mkdocs-material-custom/main.html

main.html file is now used to do any changes to base.html file. Refer to 
http://www.mkdocs.org/user-guide/styling-your-docs/. Existing  contents of the {% block content %} you are customizing has to be added + additional changes

Add Twitter, PDF share share icons to pages

---

docs/api/rest-api.md

added correct link for api-docs

---

docs/logagent/input-plugin-cassandra.md
mkdocs.yml

@megastef and @otisg  sorry for delay. Please review this PR

Add Cassandra Plugin documentation

---

docs/monitoring/spm-faq.md

- Still, there is a reference to `spm-client-setup-conf.sh` in Network Map & Chef recipe  which will be fixed by SC-3139

updated docs for proxy, region settings & jvm name

---

docs/logagent/output-plugin-prometheus-alertmanager.md

See https://github.com/sematext/logagent-js/pull/142

Document output plugin prometheus alertmanager

---

docs/sematext-docker-agent/configuration.md

update docs to match implementation

---

docs/logagent/installation-docker.md

update env var docs to match actual code

---

docs/javascripts/extra.js

@alterebro Can you tell if this was being called by anything?  Hopefully I didn't break anything.

Removed a trace of ActOn

---

docs/integration/elasticsearch.md

Added:
* agent installation instructions
* brief "which metrics to watch and alert on"
* instructions for setting up logging and correlating logs&metrics

Expand setup instructions

---

docs/monitoring/infrastructure.md

This PR adds general info about Infra app, describes how to use it, how to set it up on older installations and provides links features it brings.
Created instead of bad #83 PR.

Bsmid infra docs

---

docs/integration/kafka.md

Hi guys, this time similar changes for Kafka monitoring. I think I already incorporated all the wording/suggestion changes from the Solr/SolrCloud section, so hopefully will be easier to read :)

IN-4608 - Kafka monitoring docs adjustments

---

docs/monitoring/tag-support.md

Initially missed adding docs for serverless tags. Added them now.

Added serverless special tags

---

docs/logagent/installation-docker.md

A simple spelling correction for "arguments"

Simple spelling correction

---

docs/agents/sematext-agent/containers/metadata.md
docs/agents/sematext-agent/processes/metadata.md
docs/agents/sematext-agent/processes/metrics.md
docs/agents/sematext-agent/processes/sensitive-data.md
mkdocs.yml

This PR explains which metrics and metadata is collected for monitored processes. It also touches on how STA masks sensitive data in process's command line args.

STA process documentation

---

docs/monitoring/index.md
docs/monitoring/infrastructure.md

I've expanded on @bsmid 's initial docs for Infra with two screen captures and more explanations.
Screenshot below.

IN-1879: added more guides to the infrastructure monitoring docs

---

docs/logs/field-types.md

As I wrote in JIRA it is not possible to detect geo fields in ES. The only geofield we support in our default mappings is called geoip.

Fixed a documentation of geo fields

---

docs/agents/sematext-agent/containers/installation.md
docs/agents/sematext-agent/kubernetes/installation.md
docs/integration/docker.md

This PR adds mount of / to /hostfs for STA to all commands/configs we have in docs.

SC-3747 adjusted docs for mapping of / to /hostfs

---

docs/logagent/how-to-nginx-ingress-log-shipping.md

HowTo version of blog post:
https://docs.google.com/document/d/1k6vQUbFIcYk5IlAyPb0I9XIRuYFCnN6xg1NuP5ZFKYA/edit?usp=sharing

IN-5135 - HowTo for Nginx Ingress log shipping

---

docs/integration/index.md

Adding the same Experience integrations to the main Integrations page in the docs.

IN-5129: Added Experience integrations to main Integrations docs page

---

docs/index.md
docs/stylesheets/extra.css

I've added copy about Experience, and a new card for it. The cards are a bit prettier now as well. I've put them at the top for better visibility.

IN-5311: add experience to top level docs and make cards prettier

---

docs/experience/faq.md
mkdocs.yml

Add faq page for Experience

---

docs/logagent/changelog.md
docs/logagent/how-to-reduce-log-volume.md
docs/logagent/installation-docker.md
docs/logagent/output-filter-dropevents.md
docs/logagent/output-filter-geoip.md
docs/logagent/output-filter-kubernetes.md
docs/logagent/plugins.md
mkdocs.yml

- add kubernetes-enrichment plugin
- add geoip plugin 
- add drop-events plugin 
- add how-to-reduce-log-volume 
- add changelog for upcoming Logagent v3.x / geoip plugin breaking change

Logagent updates

---

docs/logs/search-syntax.md

Removed regular expression search because it's not actually supported

Removed regular expression search

---

docs/agents/sematext-agent/containers/installation.md
docs/agents/sematext-agent/kubernetes/installation.md

Update STA docs to keep in sync container/k8s install instructions.

update container/k8s instructions

---

docs/integration/docker.md

Turned various container events to headings

---

docs/agents/sematext-agent/jmx-attaching-containers.md
docs/monitoring/manually-setting-jmx-containers.md

This PR adds short description of Java AA attaching functionality and provides info on how to provide JMX settings manually.

SC-6593 Java AA attach docs (description + how to adjust jmx manually)

---

docs/logs/special-fields.md
docs/monitoring/tag-support.md
docs/special-tags.md
mkdocs.yml

Added the basic structure for Special Tags.
Todo: Wording.

IN-5582: Added special tags

---

docs/dashboards/chart-builder.md

Please make sure I didn't say something wrong

Tweaked wording, minor fixed, added links

---

docs/tags/common-schema.md

Feel free to merge+delete branch if OK, @adnanrahic

Fixed a 404

---

docs/agents/mobile.md

@adnanrahic  please check+merge+publish

Fixed formatting

---

docs/agents/sematext-agent/autodisco/mysql-driver.md
mkdocs.yml

Include instructions for manually copying the MySQL driver.

Mysql driver copy

---

docs/tags/common-schema.md

Added the new process tags to the common schema. LMK if we should add something more.

Add process tags common schema

---

docs/logagent/installation-docker.md
docs/logagent/output-filter-kubernetes.md

Fixed the typo in the Docker installation instructions for Logagent.

Fix #178 Docker installation instructions

---

docs/logagent/input-plugin-azure-eventhub.md
docs/logagent/plugins.md
mkdocs.yml

Need to fill in the blanks, add anything that's missing, etc.
Not added to mkdocs yet until this is ready.

Initial stub for Azure EventHub input plugin

---

docs/dashboards/chart-builder.md

Still not a very clear explanation (for me), but I think this is a little better.

Improved ordering, wording

---

docs/agents/sematext-agent/autodisco/mysql-driver.md

This PR explains how to create a PVC for the mysql driver volume.

SC-6997: create mysql PVC

---

docs/logagent/config-file.md

Added a section to show how to generate a full config file.
https://github.com/sematext/logagent-js/issues/159

Added section about complete config file

---

docs/tags/common-schema.md
docs/tags/custom-tags.md
docs/tags/index.md

Note: Feedback welcome for (1) :smile:

Updated Tags pages

---

docs/agents/sematext-agent/kubernetes/installation.md
docs/logagent/installation-docker.md

Not much to edit as the instructions in the docs state to grab the file from the Logagent repo.

Updated Logagent CRB

---

docs/logagent/input-github-webhook.md
mkdocs.yml

Added plugin page for the GitHub Webhook input plugin.

SC-7106: Added GitHub Webhook input plugin

---

docs/integration/index.md
docs/integration/journald-integration.md
mkdocs.yml

SC-7070: Added Journald integration instructions

---

docs/tags/common-schema.md

Hope I didn't break any tables...

Fixed table columns

---

docs/agents/sematext-agent/packages/data.md

Include RPM packages

---

docs/logagent/installation-docker.md

Added section about using `LA_CONFIG` to set the logagent.conf and configure multiple outputs in the `output:` section.

IN-5344: added section for log routing with LA_CONFIG for logagent container

---

docs/integration/docker.md
docs/logagent/how-to-centralize-linux-system-journal.md
docs/logagent/installation-docker.md
docs/logagent/installation-mac.md
docs/logagent/installation.md

Removed old links and replaced with new create App links.

SC-5523: cleaned up links for creating Apps

---

docs/integration/nginx.md

Used the instructions from https://apps.sematext.com/ui/howto/Nginx/overview to make the docs page better:

SC-7409: Improved Nginx monitoring integration page

---

docs/agents/sematext-agent/containers/metrics.md
docs/integration/docker.md

Docs about metrics that describe cgroup limits.

SC-7657: cgroup limit metrics

---

docs/integration/elasticsearch.md

Change SPM_ attributes prefix to ST_

SC-7763 adjust docs by switching AA SPM_ attributes to use ST_ prefix

---

docs/integration/kubernetes.md

List kuberentes metrics fields.

Kubernetes metrics fields

---

docs/experience/integrations.md

This fixes the integrations instructions to include recent updates for avoiding TypeScript and ESLint errors.

Update integrations with new instructions for TS and ESlint

---

docs/integration/vercel-logs-integration.md
mkdocs.yml

New integration under Integrations > Logs.

Added vercel logs integration

---

docs/tags/common-schema.md

Hi @otisg - have a look at the rename :)

SC-8730 - Rename fields to use geo instead of geoip

---

docs/logagent/faq.md
docs/logagent/output-filter-renamefields.md
mkdocs.yml

Added a page under output filters:
Added an entry in the FAQ:

Added docs for 'field rename' Logagent output filter

---

docs/logagent/input-plugin-command.md

This is the docs patch for https://github.com/sematext/logagent-js/pull/249

command input plugin docs for Logagent pull 249

---

docs/alerts/default-alerts.md

Be explicit about default ARs in all solutions

---

docs/agents/sematext-agent/containers/installation.md
docs/agents/sematext-agent/kubernetes/installation.md
docs/agents/sematext-agent/permission-requirements.md
mkdocs.yml

Permission requirements

---

docs/tags/common-schema.md

This PR adds IP address to common schema.

SC-9318 - Add IP address to common schema

---

docs/agents/sematext-agent/autodisco/resource-limits.md
mkdocs.yml

Explains how to override the default App Agent request/limit values.

AA request/limit settings

---

docs/index.md
docs/stylesheets/extra.css

I can't tell what colour these are, so if they are not good could you please change them?  Also, centering text may look better than having the text left aligned.

Added Mobile & Browser SDK

---

docs/monitoring/autodiscovery.md

Write docs that describe how to switch from manual to automatic monitoring

SC-9754 docs that describe how to switch between manual and automatic

---

docs/experience/integrations.md
docs/stylesheets/extra.css

This PR adds few sentences about the Next.js integration for Experience

Add next.js to Experience integrations

---

docs/synthetics/faq.md

Added basic auth entry

---

docs/synthetics/status-pages.md

This PR adds instruction for how to configure custom domains for status pages.

Add instructions for configuring custom domain for status page

---

docs/logagent/plugins.md

Fix for https://github.com/sematext/logagent-js/issues/273

Fixed link to output-plugin-http

---

docs/alerts/creating-logs-alerts.md
docs/alerts/creating-metrics-alerts.md

Just a bit of info we can point to from the new AR create screen.

Added a section about Transformations

---

docs/logs/discovery/tailing-log-files.md

update docs re change in log discovery indicators

---

docs/team/index.md
docs/team/user-roles.md

Please check the link to the new Team Account paragraph from the user-roles page.

Added a paragraph about Team Account setup

---

docs/integration/apache.md
docs/integration/elasticsearch.md
docs/integration/mongodb.md
docs/integration/nginx.md
docs/integration/nginxplus.md
docs/integration/php.md

Docs for nginx/mongo/apache were adjusted to reflect different installation procedure. Also, mongo docs got a big set of new metrics.

Sc 11390 new apache nginx mongo docs

---

docs/integration/solr.md

Once we merge this PR, I guess we'll have to re-build/release the docs. Do you know who can do that?

SC-7715 Update Solr monitor integration docs to mention logs

---

docs/experience/browser-memory.md

This PR adds the information about the requirements of website being cross-origin isolated to provide memory measurements.

Add limitations to Experience memory measurements

---

docs/agents/sematext-agent/starting-stopping.md
mkdocs.yml

Added docs to restart/stop/remove sematext agent in different environments.

SC-6754 added docs for agent restart/stop/remove

---

docs/monitoring/custom-metrics.md
docs/monitoring/index.md
mkdocs.yml

Added docs that describe how to send custom metrics using influx line protocol.

SC-5762 custom metrics docs

---

docs/integration/elasticsearch.md

Added the new metrics from https://github.com/sematext/sematext-agent-integrations/pull/46

document newly added Elasticsearch metrics

---

docs/agents/sematext-agent/containers/installation.md

Docker OSX instructions for STA in addition to clarification about collected OS metrics.

SC-11882: Docker OSX STA instructions

---

docs/faq.md

I've added this to the general FAQ, since it applies to both logs and monitoring.

Added FAQ for Apps on different envs

---

docs/synthetics/faq.md

Fix Synthetics FAQ title

---

docs/synthetics/using-the-api.md

Made amendments based on feedback from Otis, noticed a few typo's and missing information. Made further corrections.

Using the api amendments

---

docs/synthetics/browser-monitor.md
docs/synthetics/faq.md

Added information regarding what changing the device type does, as well as information on the new option to create multiple monitors in the same flow. Also added instructions on how to see if we support a certain device to the FAQ.

SC-12289 Multiple Device Types documentation

---

docs/logs/fluentbit.md
docs/logs/sending-log-events.md
mkdocs.yml

Added Fluent Bit instructions for configuring Fluent Bit with the Elasticsearch API

Added Fluen Bit Instructions

---

docs/integration/alerts-pagerduty-integration.md

New images were uploaded with https://github.com/sematext/docs/pull/406

Updated the content for PagerDuty integration.

---

docs/synthetics/faq.md

Q: Can I extract a token from a request and use it for another request?

New section added

---

docs/monitoring/spm-faq.md

https://sematext.atlassian.net/browse/SC-13974

Added FAQ entry on server info and memory devices

---

docs/monitoring/settings.md

Fix typo in Monitoring settings

---

docs/integration/solr.md

Update solr.md: replace SolrCloud references

---

docs/synthetics/using-the-api.md

Added alert priority key and values to Synthetics API create monitor.

Synthetics API - Create Monitor Alert priority

---

docs/monitoring/reports-and-components.md

Updated outdated content and screenshots. Moved time picker and live tail section from settings to this page. Added connected Apps section details.

Updated content

---

docs/monitoring/settings.md

Updated the out dated content to align with how SC behaves right now. Like I did for Logs/settings I removed the time picker and live tail component description section. These will be added to Reports & Components page along with other things such as connect Apps etc.

Updated out dated content.

---

docs/logs/settings.md

Some of the content were outdated and not aligned with how SC behaves right now. So I updated the content. Removed component descriptions like time picker, live tail. These are explained in detail in Reports & Components section. This page is more about App actions, general look, integrations and side navigations.

Content and screenshots updated

---

docs/dashboards/chart-builder.md

Screenshots updated for new CB
Component switch section added

Updated content with new CB images

---

docs/guide/integrations-guide.md

Integrations guide content updated and aligned with how SC behaves. Added missing integrations.

Content updated

---

docs/synthetics/ssl-certificate-monitoring.md

Added SSL expiry support for Browser Monitors
Added CA section

Content update

---

docs/monitoring/spm-faq.md

Update pricing for Infrastructure Monitoring

---

docs/agents/sematext-agent/containers/installation.md

Change to swarm instructions on docs

---

docs/alerts/alerts-meta.md

@fulyauluturk I think we removed this

Updating to match the new LT

---

docs/synthetics/metrics.md

How to add availability as metric in Dashboards section added

"Availability % Component" Dashboards

---

docs/monitoring/spm-faq.md

Update FAQ according to `MAX_ALLOWED_MONITOR_INTERVAL` and `MIN_ALLOWED_MONITOR_INTERVAL` from https://github.com/sematext/sematext-agent-java/blob/ef652c0b9ccb07abd85f4ed55ed11c167e93ef0f/spm-sender/src/main/java/com/sematext/spm/client/MonitorConfig.java#L44

Update spm-faq.md with monitoring interval limits

---

docs/experience/integrations.md

FYI I'll ask @harisovcinaa to have a better icon.

Micro frontend section added

---

docs/monitoring/inventory.md
docs/monitoring/processes.md

@alterebro I am not sure how to add these properly so can you review the PR and make sure everything is OK?

ful_IN-10201_add-thumbnails

---

docs/team/index.md

Configure group setting to allow posts from external emails section added.

Google Group settings added

---

docs/monitoring/autodiscovery.md

Creating PR to merge as soon as the new agent release is ready.

add varnish service

---

docs/synthetics/metrics.md
docs/synthetics/puppeteer-scripts/custom-metric-json.js
docs/synthetics/puppeteer-scripts/custom-metric.js

This PR adds info to our docs so that user are prompted to add the right name for custom metrics in BM.

Custom Metrics Naming Convention

---

docs/dashboards/quick-start.md

And add a few more general components

Give components more visibility

---

docs/agents/sematext-agent/autodisco/index.md
docs/fleet/discovery.md
docs/fleet/fleet.md
docs/fleet/index.md
docs/index.md
mkdocs.yml

Add discovery page under F&D

---

docs/logs/sending-log-events.md

Is all this still accurate after F&D?

Minor structure and wording tweaks

---

docs/agents/sematext-agent/index.md

I used 2 different links to service disco. Should we use only one?  If yes, which?

Added links, removed stale link

---

docs/synthetics/user-journey-scripts/troubleshooting.md
mkdocs.yml

This PR adds a UJS troubleshooting page, which covers some of the things we do when writing our own scripts or troubleshooting those sent to us by users. @hasan-wajahat if you have any suggestions on what to add/change feel free to mention them and I'll expand what's here. Also added @fulyauluturk as a reviewer to see if everything makes sense from the perspective of someone who doesn't deal with these scripts often.

SC-17013 Add UJS troubleshooting page

---

docs/synthetics/user-journey-scripts/examples.md

Add multi-tab browser switching example script

Add multi-tab.js

---

docs/monitoring/spm-faq.md

Add a section in Monitoring FAQ to explain how to reconfigure Sematext Agent to send metrics to another Infra App

SC-19179 reconfigure agent to send metrics to another infra app

---

docs/integration/kubernetes.md

Added supported Kubernetes distributions:
- AWS EKS
- Google GKE
- Azure AKS
- Rancher
- Red Hat OpenShift

SC-16498 add kubernetes distros

---

docs/logs/faq.md

Updated Logs troubleshooting by adding a case where all Apps are deleted, and when new ones created, Vector status is not running. In that case an Agent restart is required. This is a side case, most of the scenarios should work without an agent restart.

SC-18577: update logs troubleshooting

---

docs/agents/sematext-agent/windows-installation.md

Add warning in the Windows Agent instructions to warn users about msi installer not being properly signed

SC-19554 add msi code sign warning

---

docs/guide/features-in-this-screen.md
mkdocs.yml

Content reviewed. I'll merge this after we remove the feature flag.

Add features in this screen flyout to docs

---

docs/agents/sematext-agent/platform-support-policy.md

- Add Windows, Kubernetes, and containerized platforms to the introductory description
- Add Docker Swarm
- Add Amazon ECS
- Reorganize k8s/containers categories

Update Platform Support Policy

---

docs/monitoring/windows-services.md
mkdocs.yml

- Add a new page for Windows Services monitoring
- Metrics & Tags
- Reports (will be updated in a new PR)
- Alerts

SC-19827 add windows services page

---

docs/synthetics/browser-monitor.md
docs/synthetics/faq.md
docs/synthetics/user-journey-scripts/examples.md
docs/synthetics/user-journey-scripts/overview.md
docs/synthetics/user-journey-scripts/troubleshooting.md

Replaces references to Puppeteer with Playwright in the documentation.

SC-19286 Puppeteer to Playwright

---

docs/integration/index.md
mkdocs.yml

Restructure Integrations docs
- Overhaul Integrations Overview 
- Update left nav
- Add integrations from Experience
- Add integrations from Synthetics

SC-19968 Restructure Integrations

---

docs/agents/sematext-agent/windows-installation.md

Remove references that Sematext Agent for Windows is in beta

SC-20363 remove staw beta refs

---

docs/agents/sematext-agent/autodisco/resource-limits.md

Update App Agent resource limits page
- Added case for non k8s containers
- Improved structure

SC-20431 update App Agent resource limits page

---

docs/guide/remote-dbs-guide.md
docs/integration/index.md
docs/monitoring/spm-faq.md
mkdocs.yml

- Add guide for monitoring remote databases
- Update left nav (mkdocs)
- Reference in Monitoring FAQ
- Reference in Integration Overview

Add guide for monitoring remote databases
